import CoreGraphics
import ImageIO
import XCTest
@testable import RefereeKit

/// Validates the Swift detector against the reference Python reader's output
/// on the same image (`Fixtures/golden_expected_yolo.json`, generated by
/// running the backend's detector on `golden_crop_800.png`).
///
/// The model file is not committed; run `download-model.sh` first (or set
/// `CHESS_MODEL_PATH`). Without it these tests skip rather than fail.
final class DetectorParityTests: XCTestCase {
    private struct Golden: Decodable {
        let fen: String
        let boxes: [[Double]]
    }

    private func modelURL() throws -> URL {
        if let override = ProcessInfo.processInfo.environment["CHESS_MODEL_PATH"] {
            return URL(fileURLWithPath: override)
        }
        // RefereeKit/Tests/RefereeKitTests/ → ../../../App/Models/
        let repoLocation = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .appendingPathComponent("App/Models/yolo9t_chess.onnx")
        guard FileManager.default.fileExists(atPath: repoLocation.path) else {
            throw XCTSkip("model not downloaded; run download-model.sh or set CHESS_MODEL_PATH")
        }
        return repoLocation
    }

    private func fixtureImage() throws -> CGImage {
        let url = try XCTUnwrap(
            Bundle.module.url(forResource: "golden_crop_800", withExtension: "png", subdirectory: "Fixtures")
        )
        let source = try XCTUnwrap(CGImageSourceCreateWithURL(url as CFURL, nil))
        return try XCTUnwrap(CGImageSourceCreateImageAtIndex(source, 0, nil))
    }

    private func golden() throws -> Golden {
        let url = try XCTUnwrap(
            Bundle.module.url(forResource: "golden_expected_yolo", withExtension: "json", subdirectory: "Fixtures")
        )
        return try JSONDecoder().decode(Golden.self, from: Data(contentsOf: url))
    }

    func testReadsGoldenBoardFENExact() throws {
        let detector = try ChessDetector(modelURL: modelURL())
        let reading = try XCTUnwrap(detector.readBoard(try fixtureImage()))
        XCTAssertEqual(reading.grid.fenPlacement, try golden().fen)
    }

    func testDetectionsMatchReferenceImplementation() throws {
        let detector = try ChessDetector(modelURL: modelURL())
        let detections = try detector.detections(in: try fixtureImage())
        let reference = try golden().boxes

        // The Python reader resizes with OpenCV INTER_AREA and this port uses
        // CoreGraphics; interpolation differences shift boxes by a pixel or
        // two, so parity is judged per-box (same class, IoU > 0.8) rather
        // than bit-exact.
        var matched = 0
        for ref in reference {
            let refRect = CGRect(x: ref[0], y: ref[1], width: ref[2], height: ref[3])
            let refClass = Int(ref[5])
            if detections.contains(where: { det in
                det.classIndex == refClass
                    && iou(refRect, CGRect(x: det.x, y: det.y, width: det.width, height: det.height)) > 0.8
            }) {
                matched += 1
            }
        }
        XCTAssertGreaterThanOrEqual(
            matched, reference.count - 1,
            "only \(matched)/\(reference.count) reference detections reproduced"
        )
    }

    private func iou(_ a: CGRect, _ b: CGRect) -> Double {
        let intersection = a.intersection(b)
        guard !intersection.isNull, intersection.width > 0, intersection.height > 0 else {
            return 0
        }
        let overlap = intersection.width * intersection.height
        let union = a.width * a.height + b.width * b.height - overlap
        return union > 0 ? overlap / union : 0
    }
}
