// This file is auto-generated by @hey-api/openapi-ts

/**
 * Background-ambience bed mixed into the assistant's OUTPUT audio
 * (server-side allowlist; additionally gated by the ops flag). Presence of
 * this object enables the bed; omit it for none. Makes a telephony call
 * sound like it comes from a staffed room.
 */
export type AmbienceConfig = {
    gain_db?: number;
    track?: AmbienceTrack;
};

/**
 * Server-allowlisted ambience bed the client may request on its OUTPUT audio.
 *
 * A NAME, never a filesystem path: the server resolves it to a synthesized
 * looping bed. Adding a bed is one entry here — the resolver derives its
 * allowlist from this enum.
 */
export type AmbienceTrack = 'office';

/**
 * The agent's audio pipeline, configured once — not per run.
 */
export type AudioConfig = {
    ambience?: AmbienceConfig;
    noise_cancellation?: boolean;
    output?: boolean;
};

/**
 * Model began generating its turn (first text or audio event arrived).
 *
 * Distinct from ``bot-started-speaking`` so UI can show "thinking…" before
 * audio is on the wire — useful when the model takes a moment to start
 * generating, or when tool calls precede speech.
 */
export type BotLlmStartedEvent = {
    type: 'bot-llm-started';
};

export type BotLlmStoppedEvent = {
    type: 'bot-llm-stopped';
};

/**
 * First audio frame of an assistant turn left the server.
 *
 * Information-only — UI uses this for "speaking…" indicators / waveform
 * activation. Clients must NOT gate the mic on this event.
 */
export type BotStartedSpeakingEvent = {
    type: 'bot-started-speaking';
};

export type BotStoppedSpeakingEvent = {
    type: 'bot-stopped-speaking';
};

/**
 * Assistant TTS audio frames started flowing. With a fused-model
 * upstream this fires close to ``bot-started-speaking``; with separate
 * STT/LLM/TTS pipelines the gap is larger.
 */
export type BotTtsStartedEvent = {
    type: 'bot-tts-started';
};

export type BotTtsStoppedEvent = {
    type: 'bot-tts-stopped';
};

/**
 * Run a workspace catalog agent by handle — the stored config runs
 * verbatim. Only per-run ride-alongs may accompany the launch:
 * ``inputs`` (per-run input values), ``tools`` (client-executed
 * declarations the server cannot provide), and ``voice`` (per-run
 * speaking style plus the one cosmetic override). Other stored-config
 * fields (``instructions``, ``model``, …) are structurally absent from
 * this variant — sending one is a schema error (``extra="forbid"``), not
 * a runtime rejection.
 */
export type CatalogAgentConfig = {
    inputs?: {
        [key: string]: string;
    };
    name: string;
    tools?: Array<({
        kind?: 'client';
    } & ClientToolSpec) | ({
        kind?: 'server';
    } & ServerToolSpec) | ({
        kind?: 'catalog';
    } & CatalogToolSpec) | ({
        kind?: 'web_search';
    } & WebSearchToolSpec) | ({
        kind?: 'examine_image';
    } & ExamineImageToolSpec) | ({
        kind?: 'detect_objects';
    } & DetectObjectsToolSpec) | ({
        kind?: 'point_at_object';
    } & PointAtObjectToolSpec) | ({
        kind?: 'screen_locate';
    } & ScreenLocateToolSpec) | ({
        kind?: 'end_call';
    } & EndCallToolSpec)>;
    type: 'catalog';
    voice?: VoiceConfig;
};

/**
 * Attach a workspace-defined tool by its catalog name
 * (``voice_agent_tools.name``); the server resolves the stored definition.
 *
 * Protocol reservation only: the wire shape is fixed, but neither
 * session-start flow executes catalog tools yet — a config carrying one is
 * rejected with a typed 422 (``invalid_tool_config``). Unknown fields are
 * a schema error.
 */
export type CatalogToolSpec = {
    kind: 'catalog';
    name: string;
};

/**
 * Client signals end-of-turn for manual-VAD turn-taking. Distinct from
 * ``ClientEnd`` (whole-session teardown).
 */
export type ClientActivityEnd = {
    type: 'activity-end';
};

/**
 * Bind the agent's audio input to this client.
 *
 * Sent after the client publishes its own audio (the human voice) so the
 * agent listens to *this* participant. The server binds to the sender's
 * participant identity — a client can only bind its own input — and the pin is
 * sticky thereafter. A client that joins only to receive events or serve
 * client tools, publishing no audio, never sends this and so is never the
 * voice.
 */
export type ClientBindInput = {
    type: 'bind-input';
};

/**
 * Add text to the model's context without asking it to reply.
 *
 * The content rides the provider's pre-turn channel, so the model is never
 * asked for a response and cannot open a turn for it; it reads the note as
 * background when it next answers the user. This is the opposite of
 * ``send-text``, which *is* a turn.
 *
 * For live application state (scroll position, selection, current record,
 * form values) that should inform the agent without interrupting it.
 */
export type ClientContext = {
    content: string;
    type: 'send-context';
};

/**
 * User ended the session. Server tears down the upstream session and closes.
 */
export type ClientEnd = {
    type: 'end';
};

/**
 * Generic chunked carrier for any oversized client message.
 *
 * The SDK auto-wraps any outbound message whose JSON exceeds the
 * transport's per-packet threshold into a sequence of envelope chunks; the
 * server buffers by ``envelope_id``, concatenates the base64-encoded UTF-8
 * bytes back into the original JSON, and re-runs classification.
 *
 * ``data`` is a base64-encoded fragment of the UTF-8 bytes of the inner
 * message JSON. Base64 keeps every chunk ASCII-safe — splitting at byte
 * boundaries can land mid-codepoint in a raw UTF-8 substring, which would
 * corrupt the decode on the server.
 *
 * Ordering is guaranteed by the reliable channel (chunks arrive in ``seq``
 * order); ``envelope_id`` keeps concurrent envelopes from interleaving.
 * ``seq`` runs ``0..total-1`` and the assembler emits the reassembled
 * inner message as soon as the last chunk arrives.
 */
export type ClientEnvelope = {
    data: string;
    envelope_id: string;
    seq: number;
    total: number;
    type: 'envelope-chunk';
};

/**
 * One image frame from the client — screen share, camera capture, or
 * any other visual input the application wants to feed to the model.
 *
 * Carried as base64 in JSON so it rides the same control channel as text
 * and tool calls (the audio channel stays pure PCM). Oversized frames are
 * wrapped in ``ClientEnvelope`` chunks transparently by the SDK.
 *
 * ``stream_id`` lets the application label multiple concurrent video
 * streams (e.g. ``camera``, ``screen_share_main``).
 */
export type ClientImage = {
    data: string;
    mime_type?: string;
    stream_id?: string;
    type: 'send-image';
};

/**
 * Toggle the mic gate. While muted the client drops outbound audio frames.
 */
export type ClientMute = {
    muted: boolean;
    type: 'mute';
};

/**
 * Heartbeat. Server replies with ``PongEvent``.
 */
export type ClientPing = {
    type: 'ping';
};

/**
 * Send a text message instead of audio.
 */
export type ClientText = {
    content: string;
    type: 'send-text';
};

/**
 * One client-executed tool, self-described at session start.
 *
 * The server materializes a session-scoped tool definition from each spec,
 * so a new client tool ships with a client release alone — no per-tool
 * backend code. Field names mirror MCP's ``Tool`` descriptor.
 *
 * Only size/resource bounds are enforced here (they bind at the API edge);
 * content checks soft-reject per spec server-side and are echoed on
 * ``ReadyEvent.rejected_tools`` — a client can see *why* a spec was
 * dropped instead of debugging silence.
 */
export type ClientToolSpec = {
    description: string;
    kind: 'client';
    name: string;
    parameters: {
        [key: string]: unknown;
    };
};

/**
 * Tuning for the ``cosmo_vad`` turn detector. Every knob names the
 * detector's own machinery, so a caller always knows which endpointer a
 * setting touches; an unset knob keeps the server default.
 */
export type CosmoVadConfig = {
    max_hold_ms?: number;
    pause_ms?: number;
    prefix_ms?: number;
};

/**
 * Which of the two realtime credentials the server saw.
 */
export type CredentialKind = 'api_key' | 'user_token';

/**
 * Opt-in to the server-executed object locator, which returns boxes.
 *
 * Locates a named object in the freshest camera/screen frame — one box
 * per matching instance — and hands the candidates to the model, which
 * picks one and passes it to whichever renderer the client declared.
 * Zero-config; unknown fields are a schema error. Availability is checked
 * at session start: a deployment that cannot run the tool starts the
 * session without it and reports the drop on ``ready.rejected_tools``.
 * A session with no frame gets the tool's own typed answer at call time.
 */
export type DetectObjectsToolSpec = {
    kind: 'detect_objects';
};

/**
 * Request body for placing an outbound dial on a running session.
 */
export type DialBody = {
    /**
     * E.164 caller-ID to present, e.g. +14155550100. Must be an ACTIVE number in the workspace's pool (rejected with 400 caller_number_not_available otherwise). Omit to use the trunk default.
     */
    caller_number?: string;
    /**
     * E.164 destination to call, e.g. +14155550199.
     */
    phone_number: string;
};

/**
 * Result of ``POST /session/{id}/dial`` — the dial was queued. The
 * call rings asynchronously; ``dial_id`` is the handle to correlate it.
 * Live status / outcome is observed via session events, not this response.
 */
export type DialResponse = {
    dial_id: string;
};

/**
 * End-call action for a server hook.
 */
export type EndCall = {
    farewell?: string;
    type: 'end_call';
};

/**
 * Opt-in to the server-executed hang-up tool, so the model can end the
 * call itself once the exchange is finished.
 *
 * The server owns the model-facing declaration — zero-config; unknown
 * fields are a schema error. No availability gate: declaring it is the
 * grant. Ending binds the call, not just the agent — every leg drops —
 * and the spoken goodbye is allowed to finish playing first.
 *
 * Not the ``end_call`` silence-hook action, which hangs up on a caller who
 * stopped talking; this is the hang-up the model decides on.
 */
export type EndCallToolSpec = {
    kind: 'end_call';
};

/**
 * How readily the Gemini realtime model decides the user's turn ended.
 *
 * Mirrors ``google.genai.types.EndSensitivity`` (minus the unspecified
 * sentinel), the end-of-turn counterpart to the start-of-speech sensitivity
 * ``interruption_sensitivity`` drives. ``high`` ends the turn sooner (lower
 * endpointing latency, more likely to cut in on a mid-thought pause);
 * ``None`` keeps the provider default.
 */
export type EndOfSpeechSensitivity = 'low' | 'high';

/**
 * The error payload non-2xx external API responses carry.
 *
 * ``type`` is the error family (``api_error`` / ``validation_error`` /
 * ``internal_error``). ``code`` is the machine-readable rejection code for
 * typed session-start rejections (e.g. ``version_mismatch``,
 * ``invalid_tool_config``); absent otherwise. ``errors`` lists field-level
 * violations for ``validation_error`` responses.
 *
 * One exception: requests rejected by the authentication layer (401)
 * return ``{"detail": "..."}`` without this envelope.
 */
export type ErrorBody = {
    code?: string;
    errors?: Array<FieldError>;
    message: string;
    type: string;
};

/**
 * Stable error codes carried on wire-protocol error events; clients
 * switch on them to choose recovery behavior. Distinct from the REST
 * rejection codes carried on error envelopes (``error.code``).
 */
export type ErrorCode = 'auth_failed' | 'workspace_forbidden' | 'voice_disabled' | 'upstream_disconnect' | 'internal_error' | 'invalid_message' | 'version_mismatch';

/**
 * Wire shape of non-2xx external API responses, except auth-layer 401s
 * (which return ``{"detail": "..."}``).
 */
export type ErrorEnvelope = {
    error: ErrorBody;
};

/**
 * Recoverable or terminal error. Clients switch on ``code`` for
 * recovery UX.
 *
 * ``fatal=True`` signals the session is dead; the client should tear down
 * and reconnect rather than retry the current turn. ``fatal=False`` means
 * this turn failed but the session can continue.
 */
export type ErrorEvent = {
    code: ErrorCode;
    fatal?: boolean;
    message: string;
    type: 'error';
};

/**
 * Opt-in to the server-executed frame-examination tool.
 *
 * Reads the freshest frame of the client's published video (camera or
 * screen share) at full resolution to answer a fine-detail question.
 * The server owns the model-facing declaration — zero-config; unknown
 * fields are a schema error. Sessions without a fresh frame get the
 * tool's own typed "no frame" answer at call time; there is no
 * session-start availability gate.
 */
export type ExamineImageToolSpec = {
    kind: 'examine_image';
};

/**
 * Unstable session-config knobs.
 *
 * Fields here are experimental: unlike the rest of the protocol they may
 * change shape or disappear between releases. Stable equivalents graduate
 * to top-level ``SessionConfig`` fields.
 */
export type ExperimentalParams = {
    resume_session_id?: string;
};

/**
 * One field-level violation from request-schema validation: a path into
 * the caller's own request plus the standard validation error type and
 * message. Payload values are never echoed back.
 */
export type FieldError = {
    loc: Array<string | number>;
    msg?: string;
    type?: string;
};

/**
 * Gemini-realtime model knobs. Valid only when the selected ``model`` runs
 * on Gemini; the ``provider`` discriminator makes setting these for any other
 * provider a schema error rather than a silent no-op.
 *
 * ``turn_detection`` selects which detector ends the user's turn, and each
 * detector owns its knobs: ``end_of_speech_sensitivity``,
 * ``silence_duration_ms`` and ``prefix_padding_ms`` tune the provider's
 * ``server_vad``; the ``cosmo_vad`` block tunes ``cosmo_vad`` (the Gemini
 * default). Naming a detector and sending the other one's knobs is rejected
 * at session start rather than silently ignored.
 */
export type GeminiModelOptions = {
    cosmo_vad?: CosmoVadConfig;
    end_of_speech_sensitivity?: EndOfSpeechSensitivity;
    include_thoughts?: boolean;
    max_output_tokens?: number;
    prefix_padding_ms?: number;
    provider?: 'gemini';
    silence_duration_ms?: number;
    temperature?: number;
    thinking_level?: ThinkingLevel;
    turn_detection?: TurnDetectionMode;
};

/**
 * xAI Grok Voice model knobs. Grok pins its own sampling and token
 * limits, so only turn-taking is tunable here.
 *
 * Grok runs one detector — a fixed silence window — so the two knobs below
 * always apply. Naming any other detector is rejected at session start
 * rather than silently downgraded.
 */
export type GrokModelOptions = {
    prefix_padding_ms?: number;
    provider?: 'grok';
    silence_duration_ms?: number;
    turn_detection?: TurnDetectionMode;
};

/**
 * Define the agent inline — the persona/configuration of the model on
 * the other end, independent of any one run. Reused unchanged across
 * sessions. Catalog-only fields (``name``, ``inputs``) are structurally
 * absent — sending one is a schema error (``extra="forbid"``), so a
 * mistagged catalog launch fails loudly instead of silently running the
 * neutral default agent.
 */
export type InlineAgentConfig = {
    audio?: AudioConfig;
    greeting?: string;
    hooks?: Array<SilenceTimeout>;
    instructions?: string;
    interruption_sensitivity?: InterruptionSensitivity;
    model?: string;
    model_options?: ({
        provider?: 'gemini';
    } & GeminiModelOptions) | ({
        provider?: 'openai';
    } & OpenAiModelOptions) | ({
        provider?: 'openai_mini';
    } & OpenAiMiniModelOptions) | ({
        provider?: 'grok';
    } & GrokModelOptions);
    tools?: Array<({
        kind?: 'client';
    } & ClientToolSpec) | ({
        kind?: 'server';
    } & ServerToolSpec) | ({
        kind?: 'catalog';
    } & CatalogToolSpec) | ({
        kind?: 'web_search';
    } & WebSearchToolSpec) | ({
        kind?: 'examine_image';
    } & ExamineImageToolSpec) | ({
        kind?: 'detect_objects';
    } & DetectObjectsToolSpec) | ({
        kind?: 'point_at_object';
    } & PointAtObjectToolSpec) | ({
        kind?: 'screen_locate';
    } & ScreenLocateToolSpec) | ({
        kind?: 'end_call';
    } & EndCallToolSpec)>;
    type: 'inline';
    voice?: VoiceConfig;
};

export type InterruptionSensitivity = 'default' | 'high' | 'low';

export type MintTokenRequest = {
    /**
     * Opaque developer-supplied identifier for the end user — letters, digits, dot, underscore, plus, at-sign, or hyphen (emails work), up to 128 chars. The same value binds to the same auto-provisioned project on repeat calls.
     */
    external_user_id: string;
    /**
     * Token lifetime in seconds — between 60 and 86400 (24 hours, the default). Shorten it for tokens handed to short-lived contexts.
     */
    ttl_seconds?: number;
};

export type MintTokenResponse = {
    expires_at: string;
    jwt: string;
    /**
     * Server-side id of this minted token; pass it to DELETE /api/v1/external/auth/token/{token_id} to revoke early.
     */
    token_id: string;
};

/**
 * Streaming text-channel fragment from the model.
 *
 * Distinct from ``transcript``: this is text the model emits alongside its
 * audio output, not a transcription of the audio itself. In audio sessions
 * the upstream may write function-call narration here that the model did
 * NOT speak; in text-only sessions it carries the model's response.
 * Consumers building a "what was spoken" transcript should subscribe to
 * ``TranscriptDeltaEvent`` instead.
 */
export type ModelTextEvent = {
    is_final?: boolean;
    text: string;
    type: 'model-text';
};

/**
 * OpenAI-Realtime mini-tier model knobs — the same API as
 * ``OpenAIModelOptions`` on a faster, cheaper model, and
 * equally untunable today.
 */
export type OpenAiMiniModelOptions = {
    provider?: 'openai_mini';
};

/**
 * OpenAI-Realtime model knobs. OpenAI Realtime pins its own sampling and
 * token limits, so only turn-taking is tunable here.
 *
 * ``turn_detection`` selects which detector runs and decides which of the
 * remaining knobs apply: ``eagerness`` belongs to ``semantic_vad``, the two
 * window knobs to ``server_vad``. Sending a knob from the other mode is
 * rejected at session start rather than silently ignored.
 */
export type OpenAiModelOptions = {
    eagerness?: SemanticEagerness;
    prefix_padding_ms?: number;
    provider?: 'openai';
    silence_duration_ms?: number;
    turn_detection?: TurnDetectionMode;
};

/**
 * Opt-in to the server-executed object locator, which returns points.
 *
 * The sibling of ``detect_objects``: a marked point says one thing where
 * a box around a leaf includes everything behind it. Same zero-config and
 * availability terms.
 */
export type PointAtObjectToolSpec = {
    kind: 'point_at_object';
};

/**
 * Reply to ``ClientPing``.
 */
export type PongEvent = {
    type: 'pong';
};

/**
 * Which realtime model providers the caller may select per session.
 *
 * Clients that surface a provider picker should hide it when
 * ``openai_provider_available`` is false — a picker the server would
 * silently override is worse than no picker.
 */
export type ProviderCapabilities = {
    openai_provider_available: boolean;
};

/**
 * Sent after the upstream session is established and the agent is ready.
 */
export type ReadyEvent = {
    agent?: ResolvedAgent;
    max_session_seconds?: number;
    rejected_tools?: Array<RejectedTool>;
    session_id: string;
    type: 'ready';
};

/**
 * Server is transparently rotating the upstream session.
 *
 * Emitted after the upstream signals an imminent shutdown when the server
 * has cached a resumption handle and is reopening the model session. The
 * transport and session state survive the swap; clients can show a brief
 * "reconnecting…" indicator and otherwise stay put.
 */
export type ReconnectingEvent = {
    seconds_remaining?: number;
    type: 'reconnecting';
};

/**
 * One tool spec the server refused, with the reason — so a client can
 * log *why* a spec was dropped instead of debugging silence.
 */
export type RejectedTool = {
    name: string;
    reason: string;
};

/**
 * Resolved-agent summary echoed on ``ready`` when the session referenced a
 * registry agent (``agent.name``). Informational only — never authoritative;
 * clients don't act on it.
 */
export type ResolvedAgent = {
    name: string;
    tools?: Array<string>;
};

export type RevokeTokenResponse = {
    revoked: boolean;
};

/**
 * Idle-message action for a server hook: `text` = exact words,
 * `prompt` = model-generated per instruction, both unset = free model speech.
 */
export type Say = {
    prompt?: string;
    text?: string;
    type: 'say';
};

/**
 * Opt-in to the server-executed screen locator.
 *
 * Resolves a description to an element on the client's shared screen and
 * hands the model an opaque handle for it, which the model passes to
 * whichever screen renderer the client declared
 * (``cosmo_sdk_screen_click_element`` /
 * ``cosmo_sdk_screen_highlight_element``). Not authorable: SDKs emit this
 * entry mechanically when the host supplies a screen-capture handler, whose
 * ``screen_capture`` RPC the locator drives. Zero-config;
 * unknown fields are a schema error.
 *
 * The locator itself has no availability gate.
 * ``cosmo_sdk_screen_click_element`` does — clicking acts on the user's
 * machine, so it stays behind the desktop-control policy, and a session that
 * cannot run it starts without it and reports the drop on
 * ``ready.rejected_tools`` under that name.
 */
export type ScreenLocateToolSpec = {
    kind: 'screen_locate';
};

/**
 * Self-reported identity of the SDK that opened the session.
 *
 * ``name`` is the SDK's registry package name ("cosmo-ai-sdk" on PyPI,
 * "cosmo-ai" on npm, "cosmo-swift-sdk" for SwiftPM) — with ``version``,
 * exactly what is installed. Deployed clients keep sending the name they
 * were built with; a package rename maps the old name onto the new line
 * server-side.
 *
 * The pair is a claim, not a fact: it feeds telemetry and, for packages
 * we ship, support decisions — never authorization or billing. An unknown
 * or absent identity is bucketed, never refused.
 */
export type SdkInfo = {
    name: string;
    version: string;
};

/**
 * How eagerly OpenAI's ``semantic_vad`` closes the user's turn.
 *
 * ``low`` waits longer for the user to continue, ``high`` responds sooner;
 * ``auto`` is the provider default and behaves like ``medium``.
 */
export type SemanticEagerness = 'low' | 'medium' | 'high' | 'auto';

/**
 * Generic chunked carrier for any oversized server message.
 *
 * Mirror of ``ClientEnvelope`` for the server→client direction.
 * The server wraps any ``ServerMessage`` whose serialized JSON
 * exceeds the transport threshold into a sequence of these chunks; the SDK
 * buffers by ``envelope_id``, base64-decodes + concatenates, and
 * re-dispatches the inner message through the same handler path as
 * un-chunked messages.
 *
 * ``data`` is base64 over the UTF-8 bytes of the inner message JSON for
 * the same reason as the client side: keeps every chunk ASCII-safe so
 * byte-boundary splits never land mid-codepoint.
 */
export type ServerEnvelope = {
    data: string;
    envelope_id: string;
    seq: number;
    total: number;
    type: 'server-envelope-chunk';
};

/**
 * Opt-in to one server-executed tool by its dot-namespaced name
 * (e.g. ``"cosmo.web_search"``).
 *
 * Deprecated and no longer executed anywhere: typed per-tool kinds
 * (``web_search``, ``examine_image``, ``detect``, ``point``,
 * ``end_call``) supersede the generic name-reference, and the flow that
 * honored it is gone — a config carrying one is rejected at session start
 * with a typed 422 (``invalid_tool_config``). ``cosmo.view_state`` /
 * ``cosmo.set_state`` have no typed kinds yet, so they are unreachable
 * until they gain them.
 *
 * Server tools execute server-side; the session observes them through the
 * ``tool-call`` / ``tool-dispatch-started`` / ``tool-result`` lifecycle.
 */
export type ServerToolSpec = {
    kind: 'server';
    name: string;
};

/**
 * Session-start payload for external sessions — carried on the HTTP
 * session-start request (or as the first frame on the WS connect path).
 * The server replies with ``ReadyEvent`` once the agent is up.
 *
 * Split into the two concerns of a session: ``agent`` (the persona — what the
 * model is) and ``session`` (per-run transport options). ``sdk`` identifies
 * the client (see ``SdkInfo``).
 */
export type SessionConfig = {
    agent?: ({
        type?: 'catalog';
    } & CatalogAgentConfig) | ({
        type?: 'inline';
    } & InlineAgentConfig);
    sdk?: SdkInfo;
    session?: SessionParams;
    type: 'session-config';
};

/**
 * The server ended the session on purpose. Published just before the
 * transport tears down so clients can render a clean terminal state
 * instead of treating the room drop as a failure. Delivery is
 * best-effort — the room close may still arrive first.
 */
export type SessionEndedEvent = {
    reason: string;
    type: 'session-ended';
};

/**
 * The server will end this session shortly (e.g. the max-duration cap
 * is about to fire). Clients may show a countdown; the session keeps
 * running until ``session-ended``.
 */
export type SessionEndingSoonEvent = {
    reason: string;
    seconds_remaining: number;
    type: 'session-ending-soon';
};

/**
 * Bundle for seeding a completed call: transcript + metadata + optional audio.
 */
export type SessionImportRequest = {
    /**
     * Optional mono WAV recording, base64-encoded.
     */
    audio_wav_base64?: string;
    /**
     * Call end time, epoch seconds.
     */
    ended_at?: number;
    provider?: 'gemini' | 'openai' | 'openai_mini' | 'grok' | 'cosmo_voice_personaplex' | 'cosmo_voice_ultravox';
    /**
     * Call start time, epoch seconds.
     */
    started_at: number;
    /**
     * Display title for the session.
     */
    title?: string;
    /**
     * Ordered speech turns (user/assistant).
     */
    transcript?: Array<TranscriptTurnInput>;
};

/**
 * Per-run, transport-level options for one session — continuity and other
 * knobs that vary run-to-run for the same agent. Audio config lives on the
 * ``agent`` block (it's part of the agent, configured once).
 */
export type SessionParams = {
    experimental?: ExperimentalParams;
    max_session_seconds?: number;
    store_audio?: boolean;
    store_recording?: boolean;
    store_transcript?: boolean;
    store_video?: boolean;
};

/**
 * Developer-facing session record for the external (API-key) data-out
 * endpoints. Carries only product-agnostic fields — the workspace and the
 * end user are resolved from the credential, never echoed back.
 */
export type SessionRecord = {
    ended_at?: number;
    has_resumption_handle: boolean;
    id: string;
    provider?: 'gemini' | 'openai' | 'openai_mini' | 'grok' | 'cosmo_voice_personaplex' | 'cosmo_voice_ultravox';
    started_at: number;
    status: SessionStatus;
};

/**
 * Connection credentials for a started session.
 *
 * The client joins the LiveKit room at ``livekit_url`` with ``token``;
 * ``session_id`` correlates the session across API calls and session
 * events.
 */
export type SessionResponse = {
    /**
     * LiveKit room URL to connect to.
     */
    livekit_url: string;
    /**
     * LiveKit room name.
     */
    room_name: string;
    /**
     * Server-minted session identifier.
     */
    session_id: string;
    /**
     * Server-side session-start phase breakdown (ms).
     */
    timings?: SessionStartTimings;
    /**
     * Short-lived participant join token.
     */
    token: string;
};

/**
 * Server-side phase breakdown of session start (milliseconds).
 *
 * Mirrors the ``starter_*`` fields of the "realtime session dispatched"
 * log line. Echoed to the client so it can emit one joined
 * startup-waterfall event (server + client phases) keyed by session_id,
 * instead of leaving the join to log archaeology.
 */
export type SessionStartTimings = {
    db_insert_ms: number;
    dispatch_ms: number;
    mint_tokens_ms: number;
    project_check_ms: number;
    provider_resolve_ms: number;
    resolve_ms?: number;
    total_ms: number;
    version_check_ms: number;
};

/**
 * First-party cosmo event: live session state after a ``set_state`` tool
 * write, for rendering call progress in a client UI. Carries the
 * full canonical state, not a delta; ``stage`` is hoisted from
 * ``state["stage"]`` and ``warnings`` are the advisory schema findings the
 * model also saw in its tool result.
 */
export type SessionStateWriteEvent = {
    stage?: string;
    state?: {
        [key: string]: unknown;
    };
    type: 'cosmo.session-state';
    updated_keys?: Array<string>;
    warnings?: Array<string>;
};

export type SessionStatus = 'active' | 'completed' | 'error';

/**
 * Token usage reported by the session's model provider, split by
 * direction and modality. The live ``cosmo.usage`` event's counters plus
 * the input and output totals, with the same cumulative semantics.
 */
export type SessionTokenUsage = {
    input_audio_tokens?: number;
    input_cached_tokens?: number;
    input_image_tokens?: number;
    input_text_tokens?: number;
    input_tokens?: number;
    output_audio_tokens?: number;
    output_text_tokens?: number;
    output_tokens?: number;
    total_tokens?: number;
};

/**
 * One transcript line: timestamp (epoch seconds), speaker role, and text.
 */
export type SessionTranscriptTurn = {
    role: 'user' | 'assistant';
    text: string;
    ts: number;
};

/**
 * Usage summary for one session, in provider-reported units.
 *
 * ``duration_seconds`` is set once the session ends. The rest of the
 * detail arrives with the summary, so it is present only while
 * ``usage_status`` is ``RECORDED``, at which point the numbers are
 * final. ``tokens`` is absent when the provider reports none.
 */
export type SessionUsage = {
    agent_speaking_seconds?: number;
    duration_seconds?: number;
    model?: string;
    provider?: 'gemini' | 'openai' | 'openai_mini' | 'grok' | 'cosmo_voice_personaplex' | 'cosmo_voice_ultravox';
    status: SessionStatus;
    tokens?: SessionTokenUsage;
    turn_count?: number;
    usage_status: UsageStatus;
    user_speaking_seconds?: number;
};

/**
 * Server-runtime hook: perform `action` after `timeout_seconds` of user
 * silence.
 */
export type SilenceTimeout = {
    action: ({
        type?: 'say';
    } & Say) | ({
        type?: 'end_call';
    } & EndCall);
    max_count?: number;
    name?: string;
    reset_mode?: 'never' | 'on_user_speech';
    timeout_seconds: number;
    trigger?: 'user.speech.timeout';
};

/**
 * Reasoning depth the client may request for the Gemini realtime model.
 *
 * Mirrors ``google.genai.types.ThinkingLevel`` (minus the unspecified
 * sentinel). The server maps it onto the upstream enum; ``None`` on the init
 * leaves the server default in place.
 */
export type ThinkingLevel = 'minimal' | 'low' | 'medium' | 'high';

/**
 * Model decided to invoke a server-executed tool.
 *
 * Three-event lifecycle:
 * ``tool-call`` (model decided)
 * → ``tool-dispatch-started`` (server-side handler began)
 * → ``tool-result`` (completed).
 */
export type ToolCallEvent = {
    name: string;
    tool_call_id: string;
    type: 'tool-call';
};

/**
 * Server-side handler for the tool call began executing.
 *
 * Sits between ``tool-call`` and ``tool-result`` to let UIs show a
 * "dispatching…" state — useful for slow tools where the gap between
 * model decision and result is multiple seconds.
 */
export type ToolDispatchStartedEvent = {
    name: string;
    tool_call_id: string;
    type: 'tool-dispatch-started';
};

/**
 * Server asks the connected client to run a tool locally.
 *
 * Sent only for tools declared via ``kind="client"`` specs at session
 * start. The SDK runs the tool against the client's local resources and
 * returns the result out of band; the server validates it before
 * resolving the pending dispatch.
 *
 * ``request_id`` is the dispatch correlation id; ``tool_call_id`` is the
 * upstream's identifier for the underlying function call and is kept
 * distinct so observability messages (``tool-call`` / ``tool-result``)
 * still correlate by the upstream's id.
 *
 * ``origin`` identifies which producer authored the invocation:
 * ``"realtime"`` for the voice model (default), ``"server"`` for a
 * server tool runtime reaching back through the same bridge. Clients
 * that don't render the distinction can ignore the field.
 *
 * ``executable`` is ``False`` for an informational mirror whose execution
 * runs out-of-band; ``True`` (default, and for a missing field) means the
 * recipient runs the tool.
 */
export type ToolInvocationEvent = {
    args?: {
        [key: string]: unknown;
    };
    executable?: boolean;
    name: string;
    origin?: 'realtime' | 'server';
    request_id: string;
    tool_call_id: string;
    type: 'tool-invocation';
};

/**
 * A long-running client tool finished off-band and is delivering its
 * terminal result. The server resolves the original tool call from
 * ``job_id`` and injects the outcome; ``summary`` / ``error`` are the
 * model-facing text and ``result`` is structured data for logging.
 *
 * Half of the background client-tool primitive — a tool whose work outlives
 * the RPC reply budget acks first and lands its outcome here. Every SDK
 * implements it, so it is protocol vocabulary rather than a first-party
 * extension.
 */
export type ToolJobResult = {
    error?: string;
    job_id: string;
    result?: {
        [key: string]: unknown;
    };
    status: 'completed' | 'failed';
    summary?: string;
    tool_name: string;
    type: 'tool_job_result';
};

/**
 * Server-side tool finished. ``summary`` is a short human-readable line.
 */
export type ToolResultEvent = {
    ok: boolean;
    summary?: string;
    tool_call_id: string;
    type: 'tool-result';
};

/**
 * Streaming transcript event for either speaker.
 *
 * For the assistant role in audio sessions, this is the audio
 * transcription — the words the listener actually heard. The model may
 * ALSO emit a separate text channel via ``ModelTextEvent``; consumers
 * that render a "what was spoken" bubble should subscribe to
 * ``transcript`` only.
 *
 * Contract (wire-level, applies to both user and assistant):
 *
 * * Streaming events (``is_final=False``): ``text`` is the **new
 * fragment since the previous event** for that role's turn (a
 * delta). Consumers append.
 * * Terminating event (``is_final=True``): ``text`` is the
 * **cumulative full transcript** for the turn. Consumers replace
 * whatever they accumulated with this value.
 *
 * Two carve-outs where the terminating event is NOT the full turn, both
 * load-bearing rather than accidental:
 *
 * * **Empty final.** A turn the model produced nothing usable for (a
 * suppressed or garbled turn) finalizes with ``text=""``. It means an
 * empty turn, not "unchanged" — a consumer that skips empty finals
 * leaves the turn's bubble dangling into the next one.
 * * **Suffix final on a silent session.** When the agent runs with
 * ``audio.output=False``, a user final that arrives after the VAD
 * endpoint already committed the utterance is stripped of the committed
 * prefix, so it carries only the remainder. Replacing on final would
 * drop the part committed at the endpoint.
 *
 * A consumer that only ever appends non-finals and replaces on final is
 * correct for the common path; these two need the extra handling.
 */
export type TranscriptDeltaEvent = {
    is_final: boolean;
    role: TranscriptRole;
    text: string;
    type: 'transcript';
};

/**
 * Speaker for a transcript fragment.
 */
export type TranscriptRole = 'USER' | 'ASSISTANT';

/**
 * One transcript line: timestamp (epoch seconds), speaker role, and text.
 */
export type TranscriptTurnInput = {
    role: 'user' | 'assistant';
    text: string;
    ts: number;
};

/**
 * External TTS providers a speech-to-speech model can render.
 */
export type TtsProvider = 'elevenlabs' | 'cartesia';

/**
 * Provider-agnostic external-TTS voice selection. The runtime maps this to
 * the speech-to-speech provider's own wire format. ``voice_id`` is the TTS
 * provider's own voice id; the tuning fields apply to ElevenLabs (Cartesia
 * ignores the ElevenLabs-specific ones).
 */
export type TtsVoice = {
    model?: string;
    provider: TtsProvider;
    similarity_boost?: number;
    speed?: number;
    stability?: number;
    style?: number;
    use_speaker_boost?: boolean;
    voice_id: string;
};

/**
 * Marks the end of a turn so the client can finalize a transcript bubble.
 */
export type TurnCompleteEvent = {
    role: TranscriptRole;
    type: 'turn-complete';
};

/**
 * Which turn detector ends the user's turn.
 *
 * ``server_vad`` ends the turn on a fixed silence window;
 * ``semantic_vad`` runs OpenAI's classifier that ends it as soon as the
 * utterance reads as complete (OpenAI-only); ``cosmo_vad`` runs Cosmo's own
 * semantic detector in the realtime worker (Gemini-only). ``None`` keeps
 * the provider default: ``server_vad`` on OpenAI, ``cosmo_vad`` on
 * Gemini.
 */
export type TurnDetectionMode = 'server_vad' | 'semantic_vad' | 'cosmo_vad';

/**
 * First-party cosmo event: cumulative token usage for the live session,
 * split by direction and modality. Emitted for any external session whose
 * upstream reports usage — translation is stateless, not gated on the
 * ``cosmo`` config block.
 */
export type UsageEvent = {
    input_audio_tokens?: number;
    input_cached_tokens?: number;
    input_image_tokens?: number;
    input_text_tokens?: number;
    output_audio_tokens?: number;
    output_text_tokens?: number;
    total_tokens?: number;
    type: 'cosmo.usage';
};

/**
 * Whether a session's detailed usage summary is available.
 *
 * ``PENDING`` while the session runs and for a short window after it
 * ends, before the summary is written. ``RECORDED`` once it is there
 * and the numbers are final. ``UNAVAILABLE`` once that window has
 * passed without one arriving: a session with no turn or speech
 * activity records none, and neither does one torn down abnormally.
 */
export type UsageStatus = 'pending' | 'recorded' | 'unavailable';

/**
 * A server-runtime silence timeout fired: the user was silent past a
 * configured threshold and the server performed `action`. Observability only.
 */
export type UserSpeechTimeoutEvent = {
    action: ({
        type?: 'say';
    } & Say) | ({
        type?: 'end_call';
    } & EndCall);
    max_count: number;
    session_id: string;
    silence_ms: number;
    trigger_count: number;
    type: 'user-speech-timeout';
};

/**
 * Server-side VAD detected user voice activity start.
 *
 * Information-only — clients use this for UI indicators (mic-level
 * highlight, "listening…" label). Does NOT change client mic behavior;
 * the mic keeps streaming continuously so overlapping speech is captured.
 */
export type UserStartedSpeakingEvent = {
    type: 'user-started-speaking';
};

export type UserStoppedSpeakingEvent = {
    type: 'user-stopped-speaking';
};

/**
 * Result of a credential preflight — a 200 means the credential
 * authenticated; the fields say what it can do from here.
 */
export type VerifyResponse = {
    /**
     * Whether this credential carries the scope a session start needs. False means the credential is valid but under-scoped.
     */
    can_start_sessions: boolean;
    credential: CredentialKind;
    /**
     * The end user a minted token is bound to; null for an API key.
     */
    external_user_id?: string;
    /**
     * Whether this deployment has the default voice stack configured — LiveKit plus the default provider's key. A floor, not a per-session guarantee: a session that requests an opt-in provider is checked against that provider instead, so a start can still return 503 when this is true.
     */
    realtime_voice_available: boolean;
    /**
     * Scopes granted to this credential, e.g. ``realtime:use``.
     */
    scopes: Array<string>;
    /**
     * The workspace the credential is bound to. Present for an API key, which the workspace's own developer holds; null for a minted token, which is held by an end user.
     */
    workspace?: WorkspaceInfo;
};

/**
 * How the agent sounds: the prebuilt voice and the per-run speaking
 * style. One sub-object shared by both agent variants.
 */
export type VoiceConfig = {
    name?: string;
    speaking_style?: string;
};

/**
 * Opt-in to the server-executed web-search tool, as its own typed kind.
 *
 * The server owns the model-facing declaration (name, description, query
 * schema) — the client only opts in, so the spec carries no fields today.
 * Future configuration (result count, domain filters, freshness) lands as
 * typed fields here. Unknown fields are a schema error.
 *
 * Typed per-tool kinds supersede the generic ``kind="server"``
 * name-reference, which is deprecated and rejected at session start.
 * Availability is checked at session start: a
 * deployment or workspace that cannot run the tool starts the session
 * without it and reports the drop on ``ready.rejected_tools``.
 */
export type WebSearchToolSpec = {
    kind: 'web_search';
};

/**
 * The workspace the credential is bound to.
 */
export type WorkspaceInfo = {
    name: string;
    slug: string;
};

export type MintProjectTokenData = {
    body: MintTokenRequest;
    path?: never;
    query?: never;
    url: '/api/v1/external/auth/token';
};

export type MintProjectTokenErrors = {
    /**
     * Missing or invalid API key. Rejected by the authentication layer, so the body is ``{"detail": "..."}`` — not the error envelope.
     */
    401: {
        detail: string;
    };
    /**
     * Rejected — see ``error.code`` (typed rejections) and ``error.errors`` (field-level validation). Full rejection-code table: [Session start errors](https://platform.askcosmo.ai/docs/reference/api/session-start#errors).
     */
    422: ErrorEnvelope;
};

export type MintProjectTokenError = MintProjectTokenErrors[keyof MintProjectTokenErrors];

export type MintProjectTokenResponses = {
    /**
     * Successful Response
     */
    200: MintTokenResponse;
};

export type MintProjectTokenResponse = MintProjectTokenResponses[keyof MintProjectTokenResponses];

export type RevokeProjectTokenData = {
    body?: never;
    path: {
        token_id: string;
    };
    query?: never;
    url: '/api/v1/external/auth/token/{token_id}';
};

export type RevokeProjectTokenErrors = {
    /**
     * Missing or invalid API key. Rejected by the authentication layer, so the body is ``{"detail": "..."}`` — not the error envelope.
     */
    401: {
        detail: string;
    };
    /**
     * Rejected — see ``error.code`` (typed rejections) and ``error.errors`` (field-level validation). Full rejection-code table: [Session start errors](https://platform.askcosmo.ai/docs/reference/api/session-start#errors).
     */
    422: ErrorEnvelope;
};

export type RevokeProjectTokenError = RevokeProjectTokenErrors[keyof RevokeProjectTokenErrors];

export type RevokeProjectTokenResponses = {
    /**
     * Successful Response
     */
    200: RevokeTokenResponse;
};

export type RevokeProjectTokenResponse = RevokeProjectTokenResponses[keyof RevokeProjectTokenResponses];

export type StartRealtimeSessionData = {
    body: SessionConfig;
    path?: never;
    query?: never;
    url: '/api/v1/external/realtime/session/start';
};

export type StartRealtimeSessionErrors = {
    /**
     * Missing or invalid API key. Rejected by the authentication layer, so the body is ``{"detail": "..."}`` — not the error envelope.
     */
    401: {
        detail: string;
    };
    /**
     * Rejected — see ``error.code`` (typed rejections) and ``error.errors`` (field-level validation). Full rejection-code table: [Session start errors](https://platform.askcosmo.ai/docs/reference/api/session-start#errors).
     */
    422: ErrorEnvelope;
};

export type StartRealtimeSessionError = StartRealtimeSessionErrors[keyof StartRealtimeSessionErrors];

export type StartRealtimeSessionResponses = {
    /**
     * Successful Response
     */
    200: SessionResponse;
};

export type StartRealtimeSessionResponse = StartRealtimeSessionResponses[keyof StartRealtimeSessionResponses];

export type DialRealtimeSessionData = {
    body: DialBody;
    path: {
        session_id: string;
    };
    query?: never;
    url: '/api/v1/external/realtime/session/{session_id}/dial';
};

export type DialRealtimeSessionErrors = {
    /**
     * Missing or invalid API key. Rejected by the authentication layer, so the body is ``{"detail": "..."}`` — not the error envelope.
     */
    401: {
        detail: string;
    };
    /**
     * Rejected — see ``error.code`` (typed rejections) and ``error.errors`` (field-level validation). Full rejection-code table: [Session start errors](https://platform.askcosmo.ai/docs/reference/api/session-start#errors).
     */
    422: ErrorEnvelope;
};

export type DialRealtimeSessionError = DialRealtimeSessionErrors[keyof DialRealtimeSessionErrors];

export type DialRealtimeSessionResponses = {
    /**
     * Successful Response
     */
    200: DialResponse;
};

export type DialRealtimeSessionResponse = DialRealtimeSessionResponses[keyof DialRealtimeSessionResponses];

export type VerifyRealtimeCredentialData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/external/realtime/verify';
};

export type VerifyRealtimeCredentialErrors = {
    /**
     * Missing or invalid API key. Rejected by the authentication layer, so the body is ``{"detail": "..."}`` — not the error envelope.
     */
    401: {
        detail: string;
    };
};

export type VerifyRealtimeCredentialError = VerifyRealtimeCredentialErrors[keyof VerifyRealtimeCredentialErrors];

export type VerifyRealtimeCredentialResponses = {
    /**
     * Successful Response
     */
    200: VerifyResponse;
};

export type VerifyRealtimeCredentialResponse = VerifyRealtimeCredentialResponses[keyof VerifyRealtimeCredentialResponses];

export type ListSessionsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        before_started_at?: number;
    };
    url: '/api/v1/external/sessions';
};

export type ListSessionsErrors = {
    /**
     * Missing or invalid API key. Rejected by the authentication layer, so the body is ``{"detail": "..."}`` — not the error envelope.
     */
    401: {
        detail: string;
    };
    /**
     * Rejected — see ``error.code`` (typed rejections) and ``error.errors`` (field-level validation). Full rejection-code table: [Session start errors](https://platform.askcosmo.ai/docs/reference/api/session-start#errors).
     */
    422: ErrorEnvelope;
};

export type ListSessionsError = ListSessionsErrors[keyof ListSessionsErrors];

export type ListSessionsResponses = {
    /**
     * Successful Response
     */
    200: Array<SessionRecord>;
};

export type ListSessionsResponse = ListSessionsResponses[keyof ListSessionsResponses];

export type GetRealtimeCapabilitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/external/sessions/capabilities';
};

export type GetRealtimeCapabilitiesErrors = {
    /**
     * Missing or invalid API key. Rejected by the authentication layer, so the body is ``{"detail": "..."}`` — not the error envelope.
     */
    401: {
        detail: string;
    };
};

export type GetRealtimeCapabilitiesError = GetRealtimeCapabilitiesErrors[keyof GetRealtimeCapabilitiesErrors];

export type GetRealtimeCapabilitiesResponses = {
    /**
     * Successful Response
     */
    200: ProviderCapabilities;
};

export type GetRealtimeCapabilitiesResponse = GetRealtimeCapabilitiesResponses[keyof GetRealtimeCapabilitiesResponses];

export type ImportSessionData = {
    body: SessionImportRequest;
    path?: never;
    query?: never;
    url: '/api/v1/external/sessions/import';
};

export type ImportSessionErrors = {
    /**
     * Missing or invalid access token. Rejected by the authentication layer, so the body is ``{"detail": "..."}`` — not the error envelope.
     */
    401: {
        detail: string;
    };
    /**
     * Rejected — see ``error.code`` (typed rejections) and ``error.errors`` (field-level validation). Full rejection-code table: [Session start errors](https://platform.askcosmo.ai/docs/reference/api/session-start#errors).
     */
    422: ErrorEnvelope;
};

export type ImportSessionError = ImportSessionErrors[keyof ImportSessionErrors];

export type ImportSessionResponses = {
    /**
     * Successful Response
     */
    201: SessionRecord;
};

export type ImportSessionResponse = ImportSessionResponses[keyof ImportSessionResponses];

export type DeleteSessionData = {
    body?: never;
    path: {
        session_id: string;
    };
    query?: never;
    url: '/api/v1/external/sessions/{session_id}';
};

export type DeleteSessionErrors = {
    /**
     * Missing or invalid API key. Rejected by the authentication layer, so the body is ``{"detail": "..."}`` — not the error envelope.
     */
    401: {
        detail: string;
    };
    /**
     * Rejected — see ``error.code`` (typed rejections) and ``error.errors`` (field-level validation). Full rejection-code table: [Session start errors](https://platform.askcosmo.ai/docs/reference/api/session-start#errors).
     */
    422: ErrorEnvelope;
};

export type DeleteSessionError = DeleteSessionErrors[keyof DeleteSessionErrors];

export type DeleteSessionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteSessionResponse = DeleteSessionResponses[keyof DeleteSessionResponses];

export type GetSessionData = {
    body?: never;
    path: {
        session_id: string;
    };
    query?: never;
    url: '/api/v1/external/sessions/{session_id}';
};

export type GetSessionErrors = {
    /**
     * Missing or invalid API key. Rejected by the authentication layer, so the body is ``{"detail": "..."}`` — not the error envelope.
     */
    401: {
        detail: string;
    };
    /**
     * Rejected — see ``error.code`` (typed rejections) and ``error.errors`` (field-level validation). Full rejection-code table: [Session start errors](https://platform.askcosmo.ai/docs/reference/api/session-start#errors).
     */
    422: ErrorEnvelope;
};

export type GetSessionError = GetSessionErrors[keyof GetSessionErrors];

export type GetSessionResponses = {
    /**
     * Successful Response
     */
    200: SessionRecord;
};

export type GetSessionResponse = GetSessionResponses[keyof GetSessionResponses];

export type GetSessionTranscriptData = {
    body?: never;
    path: {
        session_id: string;
    };
    query?: never;
    url: '/api/v1/external/sessions/{session_id}/transcript';
};

export type GetSessionTranscriptErrors = {
    /**
     * Missing or invalid API key. Rejected by the authentication layer, so the body is ``{"detail": "..."}`` — not the error envelope.
     */
    401: {
        detail: string;
    };
    /**
     * Rejected — see ``error.code`` (typed rejections) and ``error.errors`` (field-level validation). Full rejection-code table: [Session start errors](https://platform.askcosmo.ai/docs/reference/api/session-start#errors).
     */
    422: ErrorEnvelope;
};

export type GetSessionTranscriptError = GetSessionTranscriptErrors[keyof GetSessionTranscriptErrors];

export type GetSessionTranscriptResponses = {
    /**
     * Successful Response
     */
    200: Array<SessionTranscriptTurn>;
};

export type GetSessionTranscriptResponse = GetSessionTranscriptResponses[keyof GetSessionTranscriptResponses];

export type GetSessionUsageData = {
    body?: never;
    path: {
        session_id: string;
    };
    query?: never;
    url: '/api/v1/external/sessions/{session_id}/usage';
};

export type GetSessionUsageErrors = {
    /**
     * Missing or invalid API key. Rejected by the authentication layer, so the body is ``{"detail": "..."}`` — not the error envelope.
     */
    401: {
        detail: string;
    };
    /**
     * Rejected — see ``error.code`` (typed rejections) and ``error.errors`` (field-level validation). Full rejection-code table: [Session start errors](https://platform.askcosmo.ai/docs/reference/api/session-start#errors).
     */
    422: ErrorEnvelope;
};

export type GetSessionUsageError = GetSessionUsageErrors[keyof GetSessionUsageErrors];

export type GetSessionUsageResponses = {
    /**
     * Successful Response
     */
    200: SessionUsage;
};

export type GetSessionUsageResponse = GetSessionUsageResponses[keyof GetSessionUsageResponses];

export type ClientOptions = {
    baseUrl: 'https://{host}' | (string & {});
};